name: webdriver
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/webdriver
version: 0.6.10
description: >
 Provides WedDriver bindings for Dart. These use the WebDriver JSON
 interface, and as such, require the use of the WebDriver remote server.

