name: webdriver
author: Dart Team <misc@dartlang.org>
description: Provides WebDriver bindings for Dart. These use the WebDriver JSON interface, and as such, require the use of the WebDriver remote server.
homepage: http://www.dartlang.org
dependencies:
  unittest: any
