name: webdriver
version: 0.10.0-pre.12
author: Marc Fisher II <fisherii@google.com>
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  crypto: '^0.9.0'
  matcher: '^0.12.0+1'
  path: '^1.3.5'
  stack_trace: '^1.3.4'
dev_dependencies:
  test: '^0.12.3+5'
