name: webdriver
version: 0.9.1
author: Google Inc.
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.9.0-dev.7.1 <2.0.0'
dependencies:
  crypto: '^0.9.0'
  matcher: '^0.11.4+1'
dev_dependencies:
  path: '^1.3.3'
  unittest: '^0.11.5+4'
